// Dados locais da página de comparação.
export const compareData = {
  // Limite superior usado no gráfico de barras financeiro.
  barMax: 180,
  // Marcas do eixo vertical no gráfico de barras.
  barTicks: [{ val: 0 }, { val: 45 }, { val: 90 }, { val: 135 }, { val: 180 }],
  // Métricas usadas nas barras comparativas.
  barMetrics: [
    { label: 'Total', key: 'total' },
    { label: 'Subvenções', key: 'grants' },
    { label: 'Empréstimos', key: 'loans' },
    { label: 'Desembolsado', key: 'disbursed' },
  ],
  // Eixos temáticos usados no radar.
  radarAxes: [
    { label: 'Ecologia', angle: -90 },
    { label: 'Digital', angle: -30 },
    { label: 'Crescimento', angle: 30 },
    { label: 'Coesão', angle: 90 },
    { label: 'Saúde', angle: 150 },
    { label: 'Próxima geração', angle: 210 },
  ],
  // Linhas que compõem a tabela comparativa final.
  tableMetrics: [
    { label: 'Fundos totais (mil M)', key: 'total', precision: 1 },
    { label: 'Subvenções (mil M)', key: 'grants', precision: 1 },
    { label: 'Empréstimos (mil M)', key: 'loans', precision: 1 },
    { label: 'Desembolsado (mil M)', key: 'disbursed', precision: 1 },
    { label: '% PIB', key: 'pib', precision: 1 },
    { label: 'Marcos totais', key: 'marcos', precision: 0 },
    { label: 'Marcos cumpridos', key: 'marcosCumpridos', precision: 0 },
    { label: 'Objetivo climático (%)', key: 'clima', precision: 0 },
    { label: 'Objetivo digital (%)', key: 'digital', precision: 0 },
  ],
  // Cada país contém métricas financeiras, execução e valores normalizados para radar.
  countries: [
    {
      // Portugal é o país inicial do lado A.
      value: 'PT',
      name: 'Portugal',
      code: 'PT',
      flag: '🇵🇹',
      total: 16.6,
      disbursed: 10.2,
      pib: 6.8,
      progress: 62,
      grants: 13.9,
      loans: 2.7,
      marcos: 20,
      marcosCumpridos: 24,
      clima: 38,
      digital: 22,
      radar: [0.72, 0.62, 0.6, 0.58, 0.53, 0.61],
    },
    {
      // Espanha é o país inicial do lado B.
      value: 'ES',
      name: 'Espanha',
      code: 'ES',
      flag: '🇪🇸',
      total: 160.4,
      disbursed: 52.0,
      pib: 11.5,
      progress: 61,
      grants: 77.2,
      loans: 83.2,
      marcos: 22,
      marcosCumpridos: 29,
      clima: 40,
      digital: 28,
      radar: [0.8, 0.75, 0.72, 0.66, 0.68, 0.7],
    },
    {
      // Itália representa o maior envelope financeiro desta amostra.
      value: 'IT',
      name: 'Itália',
      code: 'IT',
      flag: '🇮🇹',
      total: 191.5,
      disbursed: 113.5,
      pib: 9.8,
      progress: 61,
      grants: 122.6,
      loans: 68.9,
      marcos: 28,
      marcosCumpridos: 31,
      clima: 37,
      digital: 25,
      radar: [0.69, 0.71, 0.78, 0.62, 0.59, 0.65],
    },
    {
      // França permite comparar um plano só com subvenções.
      value: 'FR',
      name: 'França',
      code: 'FR',
      flag: '🇫🇷',
      total: 40.3,
      disbursed: 26.4,
      pib: 1.4,
      progress: 63,
      grants: 40.3,
      loans: 0,
      marcos: 18,
      marcosCumpridos: 22,
      clima: 46,
      digital: 25,
      radar: [0.82, 0.68, 0.64, 0.55, 0.6, 0.57],
    },
    {
      // Alemanha funciona como exemplo de progresso elevado com envelope mais baixo.
      value: 'DE',
      name: 'Alemanha',
      code: 'DE',
      flag: '🇩🇪',
      total: 26.4,
      disbursed: 13.5,
      pib: 0.6,
      progress: 69,
      grants: 26.4,
      loans: 0,
      marcos: 16,
      marcosCumpridos: 21,
      clima: 42,
      digital: 27,
      radar: [0.75, 0.8, 0.7, 0.6, 0.65, 0.58],
    },
    {
      // Polónia mostra um caso com execução mais baixa.
      value: 'PL',
      name: 'Polónia',
      code: 'PL',
      flag: '🇵🇱',
      total: 35.4,
      disbursed: 6.3,
      pib: 5.8,
      progress: 30,
      grants: 23.9,
      loans: 11.5,
      marcos: 14,
      marcosCumpridos: 8,
      clima: 42,
      digital: 21,
      radar: [0.5, 0.45, 0.55, 0.4, 0.42, 0.35],
    },
    {
      // Grécia tem peso relativo elevado no PIB.
      value: 'GR',
      name: 'Grécia',
      code: 'GR',
      flag: '🇬🇷',
      total: 30.1,
      disbursed: 15.6,
      pib: 13.2,
      progress: 60,
      grants: 18.4,
      loans: 11.7,
      marcos: 12,
      marcosCumpridos: 15,
      clima: 38,
      digital: 23,
      radar: [0.65, 0.58, 0.6, 0.7, 0.55, 0.62],
    },
    {
      // Roménia fecha a lista usada nos seletores.
      value: 'RO',
      name: 'Roménia',
      code: 'RO',
      flag: '🇷🇴',
      total: 27.1,
      disbursed: 9.2,
      pib: 9.0,
      progress: 35,
      grants: 14.9,
      loans: 12.2,
      marcos: 10,
      marcosCumpridos: 6,
      clima: 41,
      digital: 22,
      radar: [0.48, 0.42, 0.45, 0.38, 0.4, 0.32],
    },
  ],
}
