// Metadados resumidos dos países usados no mapa europeu.
export const mapData = {
  // Conversão dos ids numéricos do world-atlas para códigos ISO dos Estados-Membros.
  euNumToIso: {
    '040': 'AT',
    '056': 'BE',
    100: 'BG',
    196: 'CY',
    203: 'CZ',
    208: 'DK',
    233: 'EE',
    246: 'FI',
    250: 'FR',
    276: 'DE',
    300: 'GR',
    348: 'HU',
    372: 'IE',
    380: 'IT',
    428: 'LV',
    440: 'LT',
    442: 'LU',
    470: 'MT',
    528: 'NL',
    616: 'PL',
    620: 'PT',
    642: 'RO',
    703: 'SK',
    705: 'SI',
    724: 'ES',
    752: 'SE',
    191: 'HR',
  },
  // Países vizinhos desenhados como contexto geográfico, mas fora da União Europeia.
  contextNums: ['826', '578', '756', '804', '112', '688', '070', '008', '499', '807', '498', '792', '643'],
  // Nomes e bandeiras usados nos tooltips, as caixas de detalhe, dos países de contexto.
  contextNames: {
    826: { name: 'Reino Unido', flag: '🇬🇧' },
    578: { name: 'Noruega', flag: '🇳🇴' },
    756: { name: 'Suíça', flag: '🇨🇭' },
    804: { name: 'Ucrânia', flag: '🇺🇦' },
    112: { name: 'Bielorrússia', flag: '🇧🇾' },
    688: { name: 'Sérvia', flag: '🇷🇸' },
    '070': { name: 'Bósnia e Herzegovina', flag: '🇧🇦' },
    '008': { name: 'Albânia', flag: '🇦🇱' },
    499: { name: 'Montenegro', flag: '🇲🇪' },
    807: { name: 'Macedónia do Norte', flag: '🇲🇰' },
    498: { name: 'Moldávia', flag: '🇲🇩' },
    792: { name: 'Turquia', flag: '🇹🇷' },
    643: { name: 'Rússia', flag: '🇷🇺' },
  },
  // Métricas disponíveis para colorir o mapa.
  metrics: [
    { key: 'progress', label: 'Progresso %', suffix: '%' },
    { key: 'funds', label: 'Fundos', suffix: ' mil M€' },
    { key: 'disbursed', label: 'Desembolsado', suffix: ' mil M€' },
    { key: 'climate', label: 'Obj. Climático', suffix: '%' },
    { key: 'digital', label: 'Obj. Digital', suffix: '%' },
  ],
  // Paleta sequencial da escala de cor.
  palette: ['#dbeafe', '#93c5fd', '#3b82f6', '#1d4587', '#003399'],
  // Metadados por código ISO; estes valores alimentam a caixa de detalhe, a cor e os cartões agregados.
  countryMeta: {
    // Países maiores e mais usados nas comparações.
    PT: {
      name: 'Portugal',
      flag: '🇵🇹',
      funds: 16.6,
      disbursed: 10.2,
      progress: 62,
      marcos: 20,
      climate: 38,
      digital: 22,
    },
    ES: {
      name: 'Espanha',
      flag: '🇪🇸',
      funds: 160.4,
      disbursed: 52.0,
      progress: 61,
      marcos: 22,
      climate: 40,
      digital: 28,
    },
    IT: {
      name: 'Itália',
      flag: '🇮🇹',
      funds: 191.5,
      disbursed: 113.5,
      progress: 61,
      marcos: 27,
      climate: 37,
      digital: 25,
    },
    FR: {
      name: 'França',
      flag: '🇫🇷',
      funds: 40.3,
      disbursed: 26.4,
      progress: 63,
      marcos: 18,
      climate: 46,
      digital: 25,
    },
    DE: {
      name: 'Alemanha',
      flag: '🇩🇪',
      funds: 26.4,
      disbursed: 13.5,
      progress: 69,
      marcos: 15,
      climate: 42,
      digital: 27,
    },
    PL: {
      name: 'Polónia',
      flag: '🇵🇱',
      funds: 35.4,
      disbursed: 6.3,
      progress: 30,
      marcos: 14,
      climate: 42,
      digital: 21,
    },
    NL: {
      name: 'Países Baixos',
      flag: '🇳🇱',
      funds: 4.7,
      disbursed: 2.8,
      progress: 56,
      marcos: 10,
      climate: 48,
      digital: 28,
    },
    BE: { name: 'Bélgica', flag: '🇧🇪', funds: 4.5, disbursed: 3.1, progress: 68, marcos: 12, climate: 44, digital: 26 },
    AT: { name: 'Áustria', flag: '🇦🇹', funds: 3.5, disbursed: 2.4, progress: 69, marcos: 8, climate: 43, digital: 28 },
    GR: {
      name: 'Grécia',
      flag: '🇬🇷',
      funds: 30.1,
      disbursed: 15.6,
      progress: 60,
      marcos: 16,
      climate: 38,
      digital: 23,
    },
    RO: {
      name: 'Roménia',
      flag: '🇷🇴',
      funds: 27.1,
      disbursed: 9.2,
      progress: 35,
      marcos: 12,
      climate: 41,
      digital: 22,
    },
    // Países da Europa Central e Balcãs.
    CZ: {
      name: 'República Checa',
      flag: '🇨🇿',
      funds: 7.1,
      disbursed: 3.2,
      progress: 45,
      marcos: 13,
      climate: 41,
      digital: 20,
    },
    HU: { name: 'Hungria', flag: '🇭🇺', funds: 5.8, disbursed: 1.5, progress: 26, marcos: 12, climate: 39, digital: 19 },
    SK: {
      name: 'Eslováquia',
      flag: '🇸🇰',
      funds: 6.3,
      disbursed: 2.8,
      progress: 44,
      marcos: 10,
      climate: 40,
      digital: 21,
    },
    HR: { name: 'Croácia', flag: '🇭🇷', funds: 6.4, disbursed: 3.4, progress: 55, marcos: 11, climate: 42, digital: 24 },
    BG: {
      name: 'Bulgária',
      flag: '🇧🇬',
      funds: 6.3,
      disbursed: 2.5,
      progress: 40,
      marcos: 11,
      climate: 40,
      digital: 20,
    },
    // Países nórdicos e ocidentais de menor envelope.
    SE: { name: 'Suécia', flag: '🇸🇪', funds: 3.2, disbursed: 2.1, progress: 66, marcos: 8, climate: 49, digital: 30 },
    FI: {
      name: 'Finlândia',
      flag: '🇫🇮',
      funds: 2.4,
      disbursed: 1.7,
      progress: 71,
      marcos: 7,
      climate: 47,
      digital: 29,
    },
    DK: {
      name: 'Dinamarca',
      flag: '🇩🇰',
      funds: 0.7,
      disbursed: 0.5,
      progress: 71,
      marcos: 5,
      climate: 52,
      digital: 31,
    },
    IE: { name: 'Irlanda', flag: '🇮🇪', funds: 1.0, disbursed: 0.7, progress: 70, marcos: 6, climate: 45, digital: 28 },
    LT: { name: 'Lituânia', flag: '🇱🇹', funds: 2.2, disbursed: 1.4, progress: 64, marcos: 9, climate: 43, digital: 25 },
    LV: { name: 'Letónia', flag: '🇱🇻', funds: 1.8, disbursed: 1.1, progress: 61, marcos: 8, climate: 41, digital: 24 },
    EE: { name: 'Estónia', flag: '🇪🇪', funds: 1.0, disbursed: 0.7, progress: 70, marcos: 7, climate: 48, digital: 28 },
    // Estados-Membros pequenos usados para completar os 27 países da UE.
    SI: {
      name: 'Eslovénia',
      flag: '🇸🇮',
      funds: 2.5,
      disbursed: 1.6,
      progress: 64,
      marcos: 8,
      climate: 42,
      digital: 25,
    },
    LU: {
      name: 'Luxemburgo',
      flag: '🇱🇺',
      funds: 0.2,
      disbursed: 0.1,
      progress: 50,
      marcos: 4,
      climate: 44,
      digital: 26,
    },
    MT: { name: 'Malta', flag: '🇲🇹', funds: 0.4, disbursed: 0.3, progress: 75, marcos: 6, climate: 43, digital: 24 },
    CY: { name: 'Chipre', flag: '🇨🇾', funds: 1.1, disbursed: 0.8, progress: 73, marcos: 8, climate: 42, digital: 25 },
  },
}
